job:
  name: test
  aoi_path: data/aoi/ordesa.geojson
  target_crs: EPSG:3035
  resolution_m: 10.0
  year: 2024
  season: summer
  variables:
  - ndvi
  storage:
    kind: local_cog
    output_dir: data/outputs
