# Default settings merged into each job config
defaults:
  allowed_crs:
    - EPSG:3035
    - EPSG:4326
    - EPSG:3857
    - EPSG:25829
    - EPSG:25830
    - EPSG:25831
  resolution_m: 20
  storage:
    kind: local_cog
    output_dir: data/outputs
    bucket: openpas-hdh-dev-cache
    prefix: tiles/active

logging:
  level: INFO
  format: "[%(asctime)s] %(levelname)s - %(name)s - %(message)s"
